# Step 1. Rebuild the source code
FROM node:18-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* ./

RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

COPY src ./src
COPY public ./public
COPY next.config.js .
COPY .env.example .env.local

ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}

CMD yarn dev